### ISSUE TITLE
Re-enable Token test on custom runner

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-auth-proxy#190]
Currently we don't run a test for `--token` because it's not supported in App Engine Flex.

https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/blob/main/tests/alloydb_test.go#L101-L104

This issue is for re-enabling that test.

**Comment by jackwotherspoon** [comment]
@enocom closing this now that #500 was merged 😄
