### ISSUE TITLE
Connecting from GKE

### ISSUE THREAD

**Issue by cbusseata** [GoogleCloudPlatform/alloydb-auth-proxy#223]
Hey, I am trying to troubleshoot using alloydb-auth-proxy in GKE. I unfortunately have never been able to connect. I have an alloydb cluster/instance in the same VPC as my GKE cluster, and I am trying to use the alloydb-auth-proxy as a sidecar in my GKE cluster. However, I am getting
````
failed to connect to instance: Dial error: failed to dial (instance URI = "<INSTANCE>"): dial tcp <private IP>:5433: i/o timeout
````

Note that I also have a VM in the same VPC that I AM able to connect from using the alloydb-auth-proxy. I tried running a connectivity test, and from the GKE cluster it says "unreachable" and "Configuration analysis determines that the packet could be dropped because an internal IP address is unreachable from a public GKE cluster control plane". A connectivity test from the GKE VM succeeds, however.

I was wondering if you can share some details about how the GKE cluster needs to be configured? By chance does it require a VPC-Native cluster? Is there a way to configure a route so that it can be reached from a routes-based cluster? Or am I way off?

**Comment by enocom** [comment]
@cbusseata I think you'll need to deploy in a VPC-Native cluster to access your cluster. 

For the standard cluster, GKE does all sorts of networking magic, so even though you're running on a VM within the same VPC, from a GKE context, there's some isolation that prevents access to the VPC.

cc @hessjcg in case he'd like to add any additional information.
