### ISSUE TITLE
Connection failed out when connecting from outside of the VPC

### ISSUE THREAD

**Issue by pdiniz13** [GoogleCloudPlatform/alloydb-auth-proxy#23]
In trying to connect to either the primary or the replica i'm getting the error
failed to connect to instance: Dial error: failed to dial (instance URI = "staging/us-west3/staging/staging"): dial tcp 172.30.225.2:5433: i/o timeout

**Comment by kurtisvg** [comment]
Hi @pdiniz13 -- it sounds like wherever you are running the proxy doesn't have network connectivity to your AlloyDB instance. Please take a [look at these requirements](https://cloud.google.com/alloydb/docs/auth-proxy/connect#expandable-1), and make sure that you have network connectivity when trying to connect.

**Comment by VexpoCity** [comment]
Hello @pdiniz13,

I was having the same problem, I succeeded to connect. That auth-proxy should be installed on linux vm at google compute cloud. Choose default VPC while installing. To iinstall proxy on VM, follow instructions at documentation. Choose linux amd64 for linux version of client (as most linuxes are amd64 nowadays). Connect with access-token. If you have troubles, reach me at gdarcan@gmail.com
