### ISSUE TITLE
Connection timeout when connecting from outside a VPC

### ISSUE THREAD

**Issue by gdarcan** [GoogleCloudPlatform/alloydb-auth-proxy#24]
## Bug Description

Server runs on port 5432 but proxy is trying to connect thru 5433 then timeouts

## Example code (or command)

gcloud auth application-default print-access-token
//token retrieved xxxxxxxxx........
.\alloydb-auth-proxy-x64.exe -t xxxxxxxxx /projects/___my_project_name___/locations/europe-west3/clusters/___my_cluster_name___/instances/___my_instance_name___

## Stacktrace
dial tcp 10.117.32.2:5433: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

## Extra Details

Version: PostgresSQL 14 compatible
Type: Highly available with read pools
Location: europe-west3 (Frankfurt)

## Environment

1. OS type and version: Win11 x64
2. Proxy version: 0.1.0+windows.amd64

image is from VM instance, which connects without providing port (defaults to 5432)
and "show port;" query show the port as 5432 also
![image](https://user-images.githubusercontent.com/19612632/168169455-9fdfb2cc-dbf2-4041-b746-69760a18eb07.png)

**Comment by kurtisvg** [comment]
Hi @gdarcan,

The AlloyDB Auth Proxy connects to the AlloyDB instance via server-side proxy that listens on port 5433. Check out "[How the AlloyDB Auth proxy works](https://cloud.google.com/alloydb/docs/auth-proxy/overview#how-works)" in the documentation. 

Since your connection is timing out, it probably isn't in the same VPC as the AlloyDB instance. It looks like you are connecting on Windows for your first example, but a debian VM in the second. Is your Windows machine also apart of your VM?

**Comment by gdarcan** [comment]
Hi @kurtisvg 

I read documentation, it says it connects to alloydb instance through port 5433, but instance listens only port 5432. I can connect to instance from a VM in same vpc, only through port 5432. Also SQL command shows that db instance is configured to listen 5432 (default postgresql port). I think there's a misconfiguration

**Comment by gdarcan** [comment]
PS: Linux screenshot is from VM in Computer Engine, same VPC, command is just psql to host with local IP address at 10.117.32.2, without auth proxy

What I try to achieve is, connecting the db instance from my local computer using auth proxy and using my local db management tools to setup.

Thanks for the reply

**Comment by VexpoCity** [comment]
Hello all,

I was having the problem, I succeeded to connect. That auth-proxy should be installed on linux vm at google compute cloud. Choose default VPC while installing. To iinstall proxy on VM, follow instructions at documentation. Choose linux amd64 for linux version of client (as most linuxes are amd64 nowadays). Connect with access-token. If you have troubles, reach me at gdarcan@gmail.com

Issue can be closed

**Comment by VexpoCity** [comment]
root cause of many issue tickets is about documentation

it should be clearly written that, auth-proxy should be installed on cloud engine VM

**Comment by kurtisvg** [comment]
> it should be clearly written that, auth-proxy should be installed on cloud engine VM

It doesn't have to be installed on Cloud Engine VM, but it does need to have access to the same VPC that the AlloyDB instance is in. This is stated both in the README and in our public docs: https://cloud.google.com/alloydb/docs/auth-proxy/connect#expandable-1
