### ISSUE TITLE
Connections not being closed when using alloydb-auth-proxy 

### ISSUE THREAD

**Issue by adamstrawson** [GoogleCloudPlatform/alloydb-auth-proxy#282]
### Bug Description

We're migrating from CloudSQL to AlloyDB.  We run within GKE and use `alloydb-auth-proxy` as a sidecar container for our services.

Since moving to AlloyDB we find that the number of open connections grow over time, and are not closed when our services terminate. We are unable to see this behaviour both locally and with our previous setup using `cloud-sql-proxy`

The below graph shows the `connection` increasing over a course of 3 days, until we reach the `max_connection` limit of 1000, from where we then restarted the instance. 

![Screenshot 2023-03-09 at 16 36 51](https://user-images.githubusercontent.com/109852/224091557-5b8e1b44-e703-45d9-8e25-c1181f5d2561.png)

This behaviour is only observed when using the `alloydb-auth-proxy`.

As an example of our test
Starting connection count: 60 (`SELECT count(*)  FROM pg_stat_activity WHERE usename='{snip}';`)

1) Update our services `DATABASE_URL` to connect directly to AlloyDB
2) Restart pod
Connection count: 60
3) Restart pod
Connection count: 60
4) Update our services `DATABASE_URL` to connect to AlloyDB via its `alloydb-auth-proxy` sidecar container
5) Restart pod
Connection count: 62
7) Restart pod
Connection count: 64.

Our services are Java (Kotlin), and use HikariCP for connection pooling 

### Steps to reproduce?

See Bug Report 

### Environment

1. OS type and version: GKE, with containers using alpine
2. AlloyDB Proxy version: v1.2.1
3. Proxy invocation command (for example, `./alloydb-auth-proxy --port 6000 <INSTANCE_URI>`):
```
      args:
        - '--structured-logs'
        - '--health-check'
        - '--http-address=0.0.0.0'
        - '--port=5432'
        - '--address=0.0.0.0'
        - {INSTANCE_URI}
```

**Comment by adamstrawson** [comment]
Thanks @enocom - If it helps at all, I'm happy to hold a Google Meets to run through any of what we're seeing too.

**Comment by enocom** [comment]
As a first thought, have you tried disabling the healthchecks to see if that resolves the problem? They also open and close connections, and I'm wondering if that's where the extra connections are coming from.

**Comment by enocom** [comment]
Also what do your logs look like during this period? Do you see connections opening and closing?

**Comment by adamstrawson** [comment]
I've just tested this and no change, connections still increase. 

If it helps the connections that increase are the ones that our application opens for its connection pool, but upon SIGTERM they're not closed. It appears something within alloydb-auth-proxy prevents this closure from happening. 

These are two examples that never close. 

```
 datid |  datname  |  pid   | leader_pid | usesysid |  usename  |    application_name    | client_addr | client_hostname | client_port |         backend_start         | xact_start |          query_start          |         state_change          | wait_event_type | wait_event | state | backend_xid | backend_xmin | query_id |                      query                      |  backend_type
-------+-----------+--------+------------+----------+-----------+------------------------+-------------+-----------------+-------------+-------------------------------+------------+-------------------------------+-------------------------------+-----------------+------------+-------+-------------+--------------+----------+-------------------------------------------------+----------------
 43752 | usage | 285903 |            |    43751 | usage | PostgreSQL JDBC Driver |             |                 |          -1 | 2023-03-10 10:12:30.021959+00 |            | 2023-03-10 10:12:30.04238+00  | 2023-03-10 10:12:30.042399+00 | Client          | ClientRead | idle  |             |              |          | SET application_name = 'PostgreSQL JDBC Driver' | client backend
 43752 | usage | 285902 |            |    43751 | usage | PostgreSQL JDBC Driver |             |                 |          -1 | 2023-03-10 10:12:29.835837+00 |            | 2023-03-10 10:12:29.897575+00 | 2023-03-10 10:12:29.89761+00  | Client          | ClientRead | idle  |             |              |          | SHOW TRANSACTION ISOLATION LEVEL
```

As an idea, could there be a race condition at play here where the `alloydb-auth-proxy` sidecar is terminating before the application container, and so the proxy never receives the request to close the connections from the application?  Our setup is identical within our usage of `cloudsql-auth-proxy` so I'm not sure why this isn't observed there too though

**Comment by enocom** [comment]
Thanks for the additional info. We’re working on finding the connection leak.

**Comment by enocom** [comment]
Another thought: if you enable the Prometheus endpoint you can curl the metrics endpoint and see what the proxy thinks the open connection count is. That might help isolate this between the server and client side proxies.

**Comment by adamstrawson** [comment]
Since the proxy runs as a sidecar, the metric is reset when the pod is restarted, so for the purpose of this I've created a standalone `alloydb-auth-proxy` pod, and connected the service via that so that the metrics would persist. 

Interestingly, the metric doesn't display the behaviour. 

Start:

Postgres Connections:
```
SELECT count(*)  FROM pg_stat_activity WHERE usename='usage';
 count
-------
   4 
```

Prom Metrics:
```
key_alloydbconn_open_connections 4
```

Restart application pod

Postgres Connections:
```
SELECT count(*)  FROM pg_stat_activity WHERE usename='usage';
 count
-------
   8 
```

Prom Metrics:
```
key_alloydbconn_open_connections 4
```

Repeat restart application pod

Postgres Connections:
```
SELECT count(*)  FROM pg_stat_activity WHERE usename='usage';
 count
-------
   12 
```

Prom Metrics:
```
key_alloydbconn_open_connections 4
```

During the rolling restart of the pods, I can see `key_alloydbconn_open_connections` increase, but once the previous pod termination completes, it drops back to the previous expected figure.

**Comment by enocom** [comment]
Thank you for the detailed investigation. This points at a server side problem, but I’ll repro this and get the backend folks involved.

**Comment by adamstrawson** [comment]
If it helps the backend team at all, we have a cluster that currently has a high number of idle connections which I’ve not cleared today, incase they wanted to dive into our instance specifically to assist troubleshooting/view logs. 

I can share the info in a GCP support ticket, or I can share with Matt our GCP Customer Engineer to relay to the product team. Happy to help in any way I can.

**Comment by hessjcg** [comment]
Hi y'all.  I was able to reproduce something like this with the following test on a GKE cluster and an AlloyDB instance: 

1. Observe `SELECT count(*)  FROM pg_stat_activity WHERE usename='postgres'` return 2
2. Start up a Job that runs 5 pods that simultaneously execute `select now()` using the `psql` cli client and the AlloyDB auth proxy sidecar.
3. Observe `SELECT count(*)  FROM pg_stat_activity WHERE usename='postgres'` to stay at 2

This suggests that short lived connections through the proxy that terminate correctly are OK. 

Then I ran this test scenario:

1. Observe `SELECT count(*)  FROM pg_stat_activity WHERE usename='postgres'` return 2
2. Start up a deployment of a simple Spring Boot + Hikari + JDBC with an AlloyDB Proxy sidecar.
3. Observe `SELECT count(*)  FROM pg_stat_activity WHERE usename='postgres'` to jump to 12
4. Stop the spring boot deployment.
5. Observe `SELECT count(*)  FROM pg_stat_activity WHERE usename='postgres'` to stay at 12 when I would expect to to return to 2. It stayed at 12 permanently. 

At this point I have two hypothesis for why we aren't getting expected behavior: 
- We're using the wrong metric: `SELECT count(*)  FROM pg_stat_activity WHERE usename='postgres'` returns the high water mark for how many connections, not the current active connections. 
- There is a problem somewhere in the combination of long-lived database connections, improper termination of the connections, and the AlloyDB Proxy. 

I'm going to continue to investigate further. First to rule out the "wrong metric" hypothesis, and second to see if I can narrow down where the problem exists between Hikari, Spring Boot, and the AlloyDB Proxy.

**Comment by enocom** [comment]
The next thing to do would be to check if the sockets are open on the machine where the proxy is running.

Try `netstat -vatn` to see the open sockets and grep for `5432`.

**Comment by enocom** [comment]
This is a server-side proxy issue. We'll be following up with the backend team to fix this.

Here's what I did:

1. Started the Proxy
1. Ran a Spring Boot app with a Hikari connection pool
2. Connected with `psql` and observed all the connections with:

```
select application_name, usename, datid, datname, pid, backend_start from pg_stat_activity where usename = 'postgres' ORDER BY application_name;
```
4. Killed the Proxy without stopping the Java app
5. Observed all the local sockets also close with `netstat -vatn`
6. Observed the connections remained open on the Postgres database.

Repeating steps 2, 3, and 4 continues to make the connections rise.

**Comment by adamstrawson** [comment]
Thanks both, great to hear it’s confirmed!

Been really used to see your troubleshooting steps too, appreciate the transparency here.

**Comment by enocom** [comment]
I'm told there's a rollout in progress that already has a fix for this -- will confirm early next week and leave this open until then.

**Comment by enocom** [comment]
Rollout is done.

**Comment by adamstrawson** [comment]
Thanks @enocom - I've just tested and can confirm it's working as expected for me now too. 

Are you able to share what the root cause is, just for my own interest?

Appreciate the support on resolving this! (and @hessjcg)

**Comment by enocom** [comment]
There was a misconfigured TCP keepalive in the Proxy server that was incorrectly holding connections open, I believe.
