### ISSUE TITLE
Automatic IAM Authentication

### ISSUE THREAD

**Issue by withnale** [GoogleCloudPlatform/alloydb-auth-proxy#345]
### Feature Description

With the cloudsql-proxy the option exists for an automated IAM authenticated login when setting the auto-iam-authn command line option.  (see https://github.com/GoogleCloudPlatform/cloud-sql-proxy)

With the most recent version of gcloud-cli it is possible now to create an IAM user using...

```
 gcloud alloydb users create USERNAME --type IAM_BASED
```

Would it now be possible to build in the automated IAM login logic, which I assume should be very similar to the implementation in cloudsql-proxy?

**Comment by jackwotherspoon** [comment]
Hi @withnale! Thanks for raising a feature request on the AlloyDB Auth Proxy 😄 

Yes, now that the [AlloyDB Users API](https://cloud.google.com/alloydb/docs/reference/rest/v1/projects.locations.clusters.users) has launched into GA we should be able to at the very least start scoping out the work to add Automatic IAM database AuthN to the proxy. 

AlloyDB IAM AuthN is still in Public Preview, it should be going GA later this quarter, we will probably want to wait until then before we integrate the feature into the proxy in case of any API or design changes.

We will provide updates on this bug and use it to track progress towards the feature.

Thanks for raising this feature request, have a great day! 😄

**Comment by enocom** [comment]
Quick clarification -- that's the REST API which is available right now, but currently Auto IAM AuthN isn't available. We can't comment on the roadmap, but will update here if there's any change to all that.

**Comment by withnale** [comment]
On June 27th, it looks like the remaining backend functionality was enabled. 

"[IAM authentication for AlloyDB](https://cloud.google.com/alloydb/docs/manage-iam-authn) is available in [Preview](https://cloud.google.com/products#product-launch-stages). You can add a role to Identity and Access Management (IAM) user or service accounts that lets them log into AlloyDB instances as database users."

**Comment by withnale** [comment]
I guess I need to look at the cloudsql-proxy implementation. I had assumed that the proxy was just maintaining the necessary valid token (like the manual flow) and replacing it into the conversations to cloudsql.

**Comment by enocom** [comment]
Yes, that's effectively correct. But the mechanism for transporting the token to the backend server uses the ephemeral certificate in Cloud SQL. Presently, there's no much mechanism for AlloyDB, but again, I'll update here when that changes. ;-)

**Comment by adamstrawson** [comment]
I understand that IAM authentication for AlloyDB is now in preview, is this unblocked from being able to be supported now?

**Comment by jackwotherspoon** [comment]
@adamstrawson Yes it is now unblocked, the team is currently working on the change to support automatic IAM authentication. The work is being done with PR #423

**Comment by enocom** [comment]
@adamstrawson FWIW you can do the equivalent of Auto IAM Authentication on the direct path with either database/sql or pgx. If there's interest, I can show you how here.

**Comment by ssousa33** [comment]
@enocom , I would greatly appreciate seeing your example implementation

**Comment by enocom** [comment]
Here are some examples:

- [database/sql using Auto IAM with direct connections](https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/main/direct_database_sql_test.go)
- [pgxpool using Auto IAM with direction connections](https://github.com/GoogleCloudPlatform/alloydb-go-connector/blob/main/direct_pgxpool_test.go)

Lastly FWIW we're just about to ship this feature in the Go Connector and Proxy.
- https://github.com/GoogleCloudPlatform/alloydb-go-connector/pull/358

**Comment by enocom** [comment]
This is available now in v1.5.0 -- just pass the `--auto-iam-authn` flag.
