### ISSUE TITLE
Manual IAM Authentication not working with Proxy

### ISSUE THREAD

**Issue by hspak** [GoogleCloudPlatform/alloydb-auth-proxy#384]
### Description

I suspect this may be due to not understanding how alloyDB handles IAM authentication so I'm creating this under documentation issues.

Context: 
- There is a VM running the alloydb auth proxy with a dedicated SA that has the alloyDB client permissions. ([per recommendation](https://cloud.google.com/alloydb/docs/auth-proxy/best-practices#persistent-service))
- AlloyDB has `alloydb.iam_authentication on` set.
- AlloyDB has the IAM user created through `gcloud alloydb users create sa@my-project --region us-central1 --cluster=my-cluster --type=IAM_BASED` and the SQL statements have been run to grant this user access to the database in postgres. ([docs](https://cloud.google.com/alloydb/docs/connect-iam))
- On local, we run `gcloud compute start-iap-tunnel` to forward the proxy to our local machine.
- On local, we run 
  ```
  export PGPASSWORD=$(gcloud auth print-access-token --impersonate-service-account=sa@my-project.iam.gserviceaccount.com)
  psql -h localhost -p 5432 -U sa@my-project.iam mydb
  ```

But we get the error
```
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  AlloyDB IAM user authentication failed for user ...
```

And alloydb proxy logs offer no visibility
```
accepted connection from 1.2.3.4:42769
instance closed the connection
```

Connecting with a normal user, like `postgres` through psql works:
```
psql -h localhost -p 5432 -U postgres mydb
Password for user postgres:
```

The authentication flow in my head:
1. VM has access to `Cloud AlloyDB Client` and access to impersonate the IAM SQL user `sa@my-project`.
2. The alloydb auth proxy is run with `--impersonate-service-account=sa@my-project.iam.gserviceaccount.com`. By here, the alloydb auth proxy should have all the permissions it needs to function.
3. The `sa@my-project` has access to `Cloud AlloyDB Database User` and `Service Usage Consumer`.
4. The users have access to impersonate `sa@my-project`. By here, I expect the IAM authentication should have everything it needs to operate.

I've also tried this flow without `--impersonate-service-account=sa@my-project.iam.gserviceaccount.com` and it made no difference.

### Potential Solution

I would appreciate any pointers on where the gap is in this authentication flow and have the documentation updated to help reduce this confusion.

### Additional Details

I also have an open ticket on GCP: 45813501

**Comment by enocom** [comment]
Sorry for the slow response here.

How are you starting the AlloyDB Auth Proxy? Are you using the `--impersonate-service-account` flag?

**Comment by hspak** [comment]
Ah, sorry I missed that in the OP. Yes I am: 
```
alloydb-auth-proxy -a 0.0.0.0 --impersonate-service-account sa@$my-project.iam.gserviceaccount.com projects/my-project/locations/us-central1/clusters/my-cluster/instances/my-instance
```

**Comment by enocom** [comment]
Does the IAM principal running the Proxy have `roles/iam.serviceAccounts.serviceAccountTokenCreator` attached to it?

**Comment by hspak** [comment]
Yup. The IAM principal running the proxy VM is a member of this
```
$ gcloud iam service-accounts get-iam-policy sa@my-project.iam.gserviceaccount.com
bindings:
- members:
  - serviceAccount:vm-sa@my-project.iam.gserviceaccount.com
  - ...
  role: roles/iam.serviceAccountTokenCreator
etag: BwYAKNKwvhk=
version: 1
```

**Comment by enocom** [comment]
Let me run this experiment myself to verify it's working and maybe find what's going wrong here.

**Comment by enocom** [comment]
As a side note, have you successfully authenticated using your IAM user separate from the impersonation approach?

**Comment by hspak** [comment]
I have not. I assume that would mean providing the VM a [credentials file](https://cloud.google.com/alloydb/docs/auth-proxy/connect#make_iam_credentials_available_on_the_client_host) of `sa@my-project`? I'll give it a shot now.

**Comment by enocom** [comment]
In theory this would work on the VM without a credentials file:

```
export PGPASSWORD=$(gcloud auth print-access-token)
psql -h localhost -p 5432 -U myvm-sa@my-project.iam mydb
```

Note that Postgres doesn't accept user names that start with numbers. I'm trying to get the above to work but can't so far for whatever reason.

**Comment by hspak** [comment]
FWIW, the credentials file also fails the same way. I ran it with 
```
alloydb-auth-proxy -a 0.0.0.0 --credentials-file /etc/tmp-creds.json projects/my-project/locations/us-central1/clusters/my-cluster/instances/my-instance
```
And I confirmed it picked it up fine
```
alloydb-auth-proxy[223466]: 2023/07/12 17:47:28 Authorizing with the credentials file at "/etc/tmp-creds.json"
alloydb-auth-proxy[223466]: 2023/07/12 17:47:28 [poggio-staging.us-central1.poggio-customer-data.poggio-customer-data-primary] Listening on [::]:5432
alloydb-auth-proxy[223466]: 2023/07/12 17:47:28 The proxy has started successfully and is ready for new connections! 
```

But running this on local still doesn't work
```sh
# Separately running
gcloud --project my-project compute start-iap-tunnel my-vm --local-host-port=localhost:5432 --zone=us-central1-b

# I tried the impersonated access token
export PGPASSWORD=$(gcloud auth print-access-token --impersonate-service-account=sa@my-project.iam.gserviceaccount.com)
psql -h localhost -p 5432 -U sa@my-project.iam mydb
# Still errors with "AlloyDB IAM user authentication failed..."

# I tried my own access token like you suggested
export PGPASSWORD=$(gcloud auth print-access-token)
psql -h localhost -p 5432 -U sa@my-project.iam mydb
# Still errors with "AlloyDB IAM user authentication failed..."

# I tried not setting PGPASSWORD at all (maybe thinking the auth proxy should be able to generate the token itself from the credentials file?)
psql -h localhost -p 5432 -U sa@my-project.iam -w mydb
# But it fails with "fe_sendauth: no password supplied..."

**Comment by enocom** [comment]
OK. Let me dig in further. I wonder if we're hitting a deeper bug here.

**Comment by enocom** [comment]
I can log into my instance directly like so:

```
export PGPASSWORD=$(gcloud auth print-access-token)
psql "host=10.125.16.206 user=dbaccess@enocom-playground.iam dbname=postgres"
```

But this doesn't work

```
export PGPASSWORD=$(gcloud auth print-access-token)
psql "host=127.0.0.1 user=dbaccess@enocom-playground.iam dbname=postgres"
```

I think impersonation isn't the problem here.

**Comment by hspak** [comment]
Oh interesting. Would this mean the IAP tunnel is causing issues with `psql` here?

What does that 2nd example represent? I'm not running the auth proxy locally.

**Comment by enocom** [comment]
In both cases, I'm running the commands directly on the VM that's in the same VPC as my cluster.

The second example shows me failing to connect with manual IAM authn through the Proxy. A direct connection works, which rules out IAM permissions or auth issues.

**Comment by enocom** [comment]
Talking with the backend team, I've learned there's an issue with Proxy-based IAM authentication flows. A fix is already prepared.

I suspect when that fix is deployed, your impersonation setup with work.

Note: you only need to impersonate the SA when you're getting the PGPASSWORD. The Proxy certainly can use impersonation, but it looks like you're after impersonation of the user itself, rather than the IAM Prinicpal that runs the proxy.

**Comment by enocom** [comment]
The team is qualifying the release now and estimates a rollout to complete in three weeks. Sorry for the slow turn around on this. I'll update when the rollout is done.

**Comment by hspak** [comment]
That's great news! Thanks for all the updates, appreciate the transparency 🙏

**Comment by enocom** [comment]
Sorry for the delay here. The rollout is complete and I've confirmed IAM auth through the Proxy path is functioning.
