### ISSUE TITLE
Move Java samples into AlloyDB Java Connector

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-auth-proxy#475]
### Description

This should live with the Java Connector:

https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/tree/main/examples/java.

**Comment by jackwotherspoon** [comment]
After discussion it turns out that this repository is the proper place for these examples, we will just want to group dependencies for all examples so that we are not being spammed with dep updates for the examples.
