### ISSUE TITLE
Move Python example into AlloyDB Python Connector

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-auth-proxy#476]
### Description

This should live with the Python Connector.

https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/tree/main/examples/python

**Comment by jackwotherspoon** [comment]
After discussion it turns out that this repository is the proper place for these examples, we will just want to group dependencies for all examples so that we are not being spammed with dep updates for the examples.
