### ISSUE TITLE
Move Go example into Go Connector

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/alloydb-auth-proxy#477]
### Description

This should live with AlloyDB Go Connector:

https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/tree/main/examples/go

**Comment by jackwotherspoon** [comment]
After discussion it turns out that this repository is the proper place for these examples, we will just want to group dependencies for all examples so that we are not being spammed with dep updates for the examples.
