### ISSUE TITLE
Port --exit-zero-on-sigterm from cloud-sql-proxy

### ISSUE THREAD

**Issue by druvv** [GoogleCloudPlatform/alloydb-auth-proxy#683]
### Feature Request

We are migrating from CloudSQL Postgres to AlloyDB. As part of the migration, we need to update our CloudSQL sidecar containers to instead use the AlloyDB proxy. For cronjobs, it's important that the sidecar container exits after the main container exits. We use [kubexit](https://github.com/karlkfi/kubexit) to accomplish this. 

`cloud-sql-proxy` currently supports the [--exit-zero-on-sigterm](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/1870) flag. This changes the exit code to 0 when sigterm is received. `kubeexit` sends sigterm when the sidecar should be shut down.

Without this flag, our cronjobs report as failed because the `alloydb-auth-proxy` returns exit code `143`. 

### Alternatives Considered

A workaround to this problem we discovered is to use an inline script when launching our sidecar container. For example:
```yaml
command: ["/bin/sh", "-c", "/kubexit/kubexit /alloydb-auth-proxy ...; EXIT_CODE=$?; if [ $EXIT_CODE -eq 143 ]; then exit 0; else exit $EXIT_CODE; fi"]
```

This inline script catches exit code `143` and instead returns 0. 

While this works, it would be much nicer to port the flag over.

**Comment by enocom** [comment]
Thanks @druvv -- I thought we had ported this but see we haven't. We'll get this in the next release (early August since we're in a release freeze right now).

**Comment by druvv** [comment]
> Thanks @druvv -- I thought we had ported this but see we haven't. We'll get this in the next release (early August since we're in a release freeze right now).

Awesome! Thanks for responding quickly.
