### ISSUE TITLE
Add --help message documentation to README

### ISSUE THREAD

**Issue by FezVrasta** [GoogleCloudPlatform/alloydb-auth-proxy#709]
### Question

Hi, we are using `gcr.io/alloydb-connectors/alloydb-auth-proxy` and we are observing a huge amount of logs being generated by the container.

```
2024-09-30 13:35:38.160 CEST
2024/09/30 11:35:38 [.us-central1.default.default] accepted connection from 127.0.0.1:60560
2024-09-30 13:35:38.258 CEST
2024/09/30 11:35:38 [.us-central1.default.default] client closed the connection
2024-09-30 13:35:43.135 CEST
2024/09/30 11:35:43 [.us-central1.default.default] accepted connection from 127.0.0.1:60574
2024-09-30 13:35:43.281 CEST
2024/09/30 11:35:43 [.us-central1.default.default] client closed the connection
2024-09-30 13:35:48.135 CEST
2024/09/30 11:35:48 [.us-central1.default.default] accepted connection from 127.0.0.1:59438
2024-09-30 13:35:48.204 CEST
2024/09/30 11:35:48 [.us-central1.default.default] client closed the connection
2024-09-30 13:35:53.129 CEST
2024/09/30 11:35:53 [.us-central1.default.default] accepted connection from 127.0.0.1:59452
2024-09-30 13:35:53.199 CEST
2024/09/30 11:35:53 [.us-central1.default.default] client closed the connection
```

We reached over 1 million log entries over the past month. Is there any way to set the log level to "warn" so that these info messages are not logged to the console?

**Comment by enocom** [comment]
You're looking for the `--quiet` flag which will only log error messages.

**Comment by FezVrasta** [comment]
Thanks, I don't think that's documented though?

**Comment by enocom** [comment]
If you run `./alloydb-auth-proxy --help`, it does appear in the list of flags.

We could reproduce that help message here in the repository if that would help. WDYT?

**Comment by FezVrasta** [comment]
Yes that would be extremely helpful, having ran this project exclusively through kubernetes and its container I never had a chance to play with the CLI tool.

**Comment by enocom** [comment]
Sounds good. I'll make this an issue for doing that. Thanks again for the report.
