### ISSUE TITLE
Use --auto-iam-authn with IAM based user does not work with sqlalchemy python

### ISSUE THREAD

**Issue by sandangel** [GoogleCloudPlatform/alloydb-auth-proxy#724]
### Description

I like to use alloydb-auth-proxy instead of python language connnector. 
psql client is working when I authenticate using service account and not specifying PGPASSWORD. But sqlalchemy is throwing error when I'm not specifying password:

```sh
failed: fe_sendauth: no password supplied
```

### Potential Solution

Can you give us some guidance for using sqlalchemy with IAM based user and alloydb-auth-proxy?

**Comment by enocom** [comment]
Here's what I'd expect to see:

Start the Auth Proxy like this:

``` shell
# starts a listener on port 5432 by default
# also assumes private IP, use the `--public-ip` or `--psc` flag otherwise
./alloydb-auth-proxy <INSTANCE_URI> --auto-iam-authn
```

Connect from SQL Alchemy like this:

``` python
import sqlalchemy

engine = sqlalchemy.create_engine(
        "postgresql+pg8000://localhost/postgres", # or whatever database you want to connect to
)

# use engine as usual
```

**Comment by sandangel** [comment]
Thank you so much for replying. I tried that already:

```yaml
          args:
            - --auto-iam-authn
            - --public-ip
            - --address=0.0.0.0
            - --http-address=0.0.0.0
            - --health-check
            - --prometheus
            - --run-connection-test
            - --debug
            - --quitquitquit
            - --structured-logs
```


But still got error:

```sh
failed: fe_sendauth: no password supplied
```

**Comment by sandangel** [comment]
oh, do you mean no need to put IAM user? Right now I'm using this user and use empty password like this:

```sh
postgresql+asyncpg://mv-svc\%40my-project.iam@localhost:5432/mydb
```

**Comment by sandangel** [comment]
oh it seems working now. Thank you so much.

**Comment by enocom** [comment]
You can check your Auth Proxy logs to confirm -- it will report on connections being established and so-on. Glad it's working. Feel free to re-open if you have any other questions.

**Comment by sandangel** [comment]
For others who face similar issue. I had to put PGUSER to match the alloydb-auth-proxy user for it to work.

```yaml

      # Still need to set PGUSER to match service account alloydb-auth-proxy is using
      - PGUSER=svc-alloydb@my-project.iam
      # Should not have user or password, which will be handled by alloydb-auth-proxy
      - DATABASE_URL='postgresql+asyncpg://localhost/mydb'
 ```

**Comment by enocom** [comment]
This is a common misunderstanding -- for Auto IAM AuthN to work the database user *must* match the Proxy IAM user.

**Comment by enocom** [comment]
You can put that IAM user in the connection string, but the at sign `@` will confuse some drivers and might need escaping.

**Comment by enocom** [comment]
Sounds good. I'll try to experiment with this and see what kind of escaping has to happen to make it work. FWIW other languages struggle with the `@` too because using Postgres drivers interpret that as the start of the host (instead of part of the user).

**Comment by sandangel** [comment]
I already escaped that `@` like this: https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/issues/724#issuecomment-2489049049

 but still have same issue `failed: fe_sendauth: no password supplied`. I don't know why though.

**Comment by sandangel** [comment]
notice that I also needed to escape `\%` , otherwise the sqlalchemy will report string interpolation is not correct.

**Comment by rhatgadkar-goog** [comment]
To escape the `@` symbol in the username, we need to use `%40`. This is stated in the sqlalchemy documentation: https://docs.sqlalchemy.org/en/20/core/engines.html#escaping-special-characters-such-as-signs-in-passwords.

If my username is `user@example.com`, the following worked for me: `"postgresql+pg8000://user%40example.com@localhost/postgres"`.
