### ISSUE TITLE
quitquitquit doesn't accept GET method

### ISSUE THREAD

**Issue by kchygoe** [GoogleCloudPlatform/alloydb-auth-proxy#725]
### Bug Description

`cloud-sql-proxy` accepts GET method for the `/quitquitquit` endpoint but `alloydb-auth-proxy` doesn't

### Example code (or command)

```go
// paste your code here
```

### Steps to reproduce?

1. ?
2. ?
3. ?
...

### Environment

1. OS type and version: linux
2. AlloyDB Proxy version: v1.11.3
3. Proxy invocation command (for example, `./alloydb-auth-proxy --port 6000 <INSTANCE_URI>`): `--quitquitquit`

### Additional Details

https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/blob/main/cmd/root.go#L1197

**Comment by enocom** [comment]
Fixed in https://github.com/GoogleCloudPlatform/alloydb-auth-proxy/pull/726.
