### ISSUE TITLE
Question - How to set database level permissions

### ISSUE THREAD

**Issue by Rossco8** [GoogleCloudPlatform/alloydb-auth-proxy#98]
I don't see anywhere in the documentation how to grant database level permissions for AlloyDB

In CloudSQL when we wanted to grant a service account DB level access we simply created a DB user with the `.iam` suffix eg
```
gcloud sql users create $MY_SVC_ACCOUNT@${PROJECT_ID}.iam
```

If I want to grant permissions to only 1 table or schema 
```
psql grant all on all tables in schema my_schema $MY_SVC_ACCOUNT@${PROJECT_ID}.iam
```

what is the equivilent in AlloyDB?

**Comment by kurtisvg** [comment]
Hi @Rossco8,

This repo is limited in scope to the AlloyDB Auth proxy -- your question is more general and [would be more appropriate on StackOverflow under the google-alloydb tag](https://stackoverflow.com/questions/tagged/google-alloydb). 

However, to answer your question:
1. AlloyDB doesn't support Cloud SQL's IAM DB Authentication
2. AlloyDB also doesn't have an API for creating users (aka `gcloud sql users create`).

This means that you need to use the postgres user (which password you set with the cluster was created) to [create more database users](https://www.postgresql.org/docs/14/sql-createuser.html) `CREATE USER name` and then grant appropriate roles to said user as needed.

**Comment by adamstrawson** [comment]
Hey @kurtisvg Sorry to jump on an old thread, with regards to the below:

> AlloyDB doesn't support Cloud SQL's IAM DB Authentication

Do you know if that's still the case? The Documentation seems to indicate it does now as there are references to IAM roles within AlloyDB but in reality that doesn't appear to be correct. I was going to ask our GCP Lead, but thought it might be quicker here in the mean time?
